<?php

namespace AppBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findInfosByAdresse($adresse)
    {
        $fields = array('i.commune');
        return $this->createQueryBuilder('i')
            ->select($fields)
            ->distinct()
            ->andWhere('i.commune LIKE :adresse')
            ->setParameter('adresse', '%'.$adresse.'%')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findInfosByCommune($commune)
    {
        $fields = array('i.codeInsee','i.commune','i.centroidXEtrs3035','i.centroidYEtrs3035','i.dateIndiceSupervise','i.echeance','i.dateEcheance','i.libelleQualiteAir','i.couleurCarteGe','i.libellePolluantResponsable');
        return $this->createQueryBuilder('i')
            ->select($fields)
            ->andWhere('i.commune = :commune')
            ->setParameter('commune', $commune)
            ->getQuery()
            ->getResult()
            ;
    }
}
