<?php

namespace AppBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInfosByAdresse($adresse){
        $fields = array('i.codeInsee','i.commune','i.centroidXEtrs3035','i.centroidYEtrs3035','i.dATEINDICESUPERVISE','i.eCHEANCE','i.dATEECHEANCE','i.lIBELLEQUALITEAIR','i.cOULEURCARTEGE','i.lIBELLEPOLLUANTRESPONSABLE');
        return $this->createQueryBuilder('i')
            ->select($fields)
            ->andWhere('i.codeInsee LIKE :adresse')
            ->orWhere('i.commune LIKE :adresse')
            ->setParameter('adresse', '%'.$adresse.'%')
            ->getQuery()
            ->getResult()
            ;
    }
}
