<?php

namespace AppBundle\Repository;

/**
 * associationCoProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class informationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllOrderedByName()
    {


    }

}