<?php

namespace AppBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInfosByAdresse($adresse){
        $fields = array('i.commune');
        return $this->createQueryBuilder('i')
            ->select($fields)->distinct()
            ->andWhere('i.commune LIKE :adresse')
            ->setParameter('adresse', '%'.$adresse.'%')
            ->getQuery()
            ->getResult()
            ;
    }
}
